CREATE TABLE 'fireworks' (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, color TEXT, type TEXT, noise TEXT);
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("The Big Boy", "Red", "Rocket", "Bang");
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("Water Falls", "Blue", "Fountain", "Fizz");
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("Rotar Motor", "Green", "Cathrine Wheel", "Whizz");
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("The Dieing Ghost", "White", "Screamer", "Eeek");
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("Asda Firework 1", "Brown", "Rocket", "Pop");
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("Asda Firework 2", "Green", "Rocket", "Bang");
INSERT INTO 'fireworks' (name, color, type, noise) VALUES ("Asda Firework 3", "Green and Brown", "Fountain", "Fizz");